[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
upload_port = /dev/esp-laundry  ; Your fixed symlink
monitor_port = /dev/esp-laundry
monitor_speed = 9600

lib_deps =
  knolleary/PubSubClient